name: Release Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR title
        id: get_title
        run: echo "::set-output name=title::$(echo '${{ github.event.pull_request.title }}')"

      - name: Validate Semantic Versioning Tag in PR Title
        id: version_check
        run: |
          # Extract version tag from the PR title using regex
          TITLE="${{ steps.get_title.outputs.title }}"
          VERSION_REGEX="v?([0-9]+)\.([0-9]+)\.([0-9]+)"
          if [[ $TITLE =~ $VERSION_REGEX ]]; then
            echo "Found valid version tag: ${BASH_REMATCH[0]}"
          else
            echo "Error: PR title does not contain a valid version tag (expected format vX.Y.Z)."
            exit 1
          fi

      - name: Ensure release notes are provided in PR description
        run: |
          NOTES="${{ github.event.pull_request.body }}"
          echo "Checking for release notes in the PR description..."

          # Check if release notes exist
          if [[ -z "$NOTES" ]]; then
            echo "❌ Release notes are missing. Please include detailed changes, fixes, and improvements."
            exit 1
          fi

          # Optionally enforce a minimum character length for meaningful release notes (e.g., 20 characters)
          if [[ ${#NOTES} -lt 20 ]]; then
            echo "❌ Release notes are too short. Please provide more details."
            exit 1
          fi

          echo "✅ Release notes are present and sufficiently detailed."
